from __future__ import annotations

import json
import re
from dataclasses import dataclass, asdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


@dataclass
class Source:
    name: str
    url: str
    group_title: str = ""
    country: str = ""
    language: str = ""
    enabled: bool = True
    headers: dict[str, str] | None = None


@dataclass
class Channel:
    name: str
    url: str
    group_title: str = ""
    country: str = ""
    language: str = ""
    tvg_id: str = ""
    logo: str = ""
    source: str = ""
    valid: bool | None = None
    status_code: int | None = None
    latency_ms: int | None = None
    content_type: str = ""
    error: str = ""


def load_sources(path: str | Path) -> list[Source]:
    data = json.loads(Path(path).read_text(encoding="utf-8"))
    if isinstance(data, dict):
        data = data.get("sources", [])
    if not isinstance(data, list):
        raise ValueError("sources file must be a list or an object with a sources list")

    sources: list[Source] = []
    for item in data:
        if not item.get("enabled", True):
            continue
        sources.append(
            Source(
                name=str(item.get("name") or "Unnamed source"),
                url=str(item["url"]),
                group_title=str(item.get("group-title") or item.get("group") or ""),
                country=str(item.get("country") or ""),
                language=str(item.get("language") or ""),
                enabled=bool(item.get("enabled", True)),
                headers=item.get("headers") or None,
            )
        )
    return sources


def parse_extinf_attrs(line: str) -> dict[str, str]:
    attrs: dict[str, str] = {}
    rest = line[len("#EXTINF:") :]
    for match in re.finditer(r'([a-zA-Z0-9-]+)="([^"]*)"', rest):
        key, value = match.groups()
        attrs[key] = value
    return attrs


def parse_m3u(text: str, source_name: str, defaults: Source) -> list[Channel]:
    lines = [line.strip() for line in text.splitlines() if line.strip()]
    channels: list[Channel] = []
    pending: dict[str, str] | None = None

    for line in lines:
        if line.startswith("#EXTINF:"):
            pending = parse_extinf_attrs(line)
            rest = line[len("#EXTINF:") :]
            display_name = rest.rsplit(",", 1)[-1].strip() if "," in rest else ""
            pending["display-name"] = display_name
            continue
        if line.startswith("#"):
            continue

        if not pending and not line.startswith("http"):
            continue

        name = (pending or {}).get("tvg-name") or (pending or {}).get("display-name") or defaults.name
        channel = Channel(
            name=name,
            url=line,
            group_title=(pending or {}).get("group-title") or defaults.group_title,
            country=(pending or {}).get("country") or defaults.country,
            language=(pending or {}).get("language") or defaults.language,
            tvg_id=(pending or {}).get("tvg-id", ""),
            logo=(pending or {}).get("tvg-logo", ""),
            source=source_name,
        )
        channels.append(channel)
        pending = None

    return channels


def normalize_url(url: str) -> str:
    return url.strip().split("#", 1)[0]


def dedupe_channels(channels: list[Channel]) -> list[Channel]:
    seen: set[str] = set()
    result: list[Channel] = []
    for channel in channels:
        key = normalize_url(channel.url).lower()
        if key in seen:
            continue
        seen.add(key)
        result.append(channel)
    return result


def build_m3u(channels: list[Channel]) -> str:
    lines = ["#EXTM3U", f"# Generated by IPTV Ultimate at {datetime.now(timezone.utc).isoformat()}"]
    for channel in channels:
        attrs = [
            'tvg-name="{}"'.format(channel.name.replace('"', "'")),
            'group-title="{}"'.format(channel.group_title.replace('"', "'")),
        ]
        if channel.country:
            attrs.append('country="{}"'.format(channel.country.replace('"', "'")))
        if channel.language:
            attrs.append('language="{}"'.format(channel.language.replace('"', "'")))
        if channel.tvg_id:
            attrs.append('tvg-id="{}"'.format(channel.tvg_id.replace('"', "'")))
        if channel.logo:
            attrs.append('tvg-logo="{}"'.format(channel.logo.replace('"', "'")))
        lines.append("#EXTINF:-1 {},{}".format(" ".join(attrs), channel.name))
        lines.append(channel.url)
    return "\n".join(lines) + "\n"


def write_json(path: str | Path, payload: dict[str, Any]) -> None:
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")


def channels_to_payload(channels: list[Channel], source_path: str | Path) -> dict[str, Any]:
    return {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "source": str(source_path),
        "channels": [asdict(channel) for channel in channels],
    }
